# Generated by Django 5.1.4 on 2024-12-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_faq_mediafile_payment_pricingplan_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_bookings', to='services.service'),
        ),
    ]
