# Generated by Django 5.1.4 on 2024-12-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_booking_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='preferred_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='preferred_time',
            new_name='time',
        ),
    ]
